services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=banco_db
      - POSTGRES_USER=usuario_banco
      - POSTGRES_PASSWORD=password_seguro
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U usuario_banco -d banco_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: ./bancoV2
    volumes:
      - ./bancoV2:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_NAME=banco_db
      - DATABASE_USER=usuario_banco
      - DATABASE_PASSWORD=password_seguro
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: